---
# tasks file for nodejs
  - name: download nodejs from source
    unarchive:
      src: https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-x64.tar.xz
      dest: /usr/local
      remote_src: yes
      creates: /usr/local/node-v20.11.1-linux-x64

  - name: symlink node to node
    file:
      src: /usr/local/node-v20.11.1-linux-x64/bin/node
      dest: /usr/local/bin/node
      state: link
      force: yes

  - name: symlink npm to npm
    file:
      src: /usr/local/node-v20.11.1-linux-x64/bin/npm
      dest: /usr/local/bin/npm
      state: link
      force: yes

  - name: symlink npx to npx
    file:
      src: /usr/local/node-v20.11.1-linux-x64/bin/npx
      dest: /usr/local/bin/npx
      state: link
      force: yes

  - name: install yarn
    npm:
      name: yarn
      global: yes
